### ISSUE TITLE
Editor never loads

### ISSUE THREAD

**Issue by ThePyrotechnic** [EXKing-Editor/EXKing-Editor#21]
On Linux, trying to open a bgyml file will cause the editor to hang on a blank screen. Usually closing this blank editor page will not crash the program, but subsequently interacting with other areas of the UI will eventually cause the program to crash (sorry, could not find a pattern)

```bash
╰─>$ uname -a
Linux Arch 6.3.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 May 2023 16:15:22 +0000 x86_64 GNU/Linux
╰─>$ dotnet --version
7.0.103
```

output after opening a bgyml file:
```bash
╰─>$ ./EX-King-Editor-0.3.2-alpha
29:57:02:608 [TryLoadEditor] | "../../../../../../../../home/runner/work/EXKing-Editor/EXKing-Editor/src/ExKingEditor/Models/EditorMgr.cs":29 | Processing Armor_182_Head.pack.zs
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7437765)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7437765)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #66939890)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #66939890)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #65588106)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #65588106)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #53422044)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #53422044)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #11036355)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #11036355)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #32218335)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #32218335)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #21529561)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #21529561)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #55844233)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #55844233)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #27089021)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #27089021)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #17890920)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #17890920)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #26800560)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #26800560)
29:57:14:626 [TryLoadEditor] | "../../../../../../../../home/runner/work/EXKing-Editor/EXKing-Editor/src/ExKingEditor/Models/EditorMgr.cs":29 | Processing Armor_182_Head.engine__component__ModelInfo.bgyml
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7437765)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7437765)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #66939890)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #66939890)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #65588106)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #65588106)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #53422044)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #53422044)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #11036355)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #11036355)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #32218335)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #32218335)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #21529561)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #21529561)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #55844233)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #55844233)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #27089021)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #27089021)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #17890920)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #17890920)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #26800560)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.DataTriggerBehavior'.'Binding': 'Null value in expression '{empty}' at ''.'(DataTriggerBehavior #26800560)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.ChangePropertyAction'.'TargetObject': 'Null value in expression '{empty}' at '$parent[Button, 0]'.'(ChangePropertyAction #41000636)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.ChangePropertyAction'.'TargetObject': 'Null value in expression '{empty}' at '$parent[Button, 0]'.'(ChangePropertyAction #41000636)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.ChangePropertyAction'.'TargetObject': 'Null value in expression '{empty}' at '$parent[Button, 0]'.'(ChangePropertyAction #33461405)
[Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.ChangePropertyAction'.'TargetObject': 'Null value in expression '{empty}' at '$parent[Button, 0]'.'(ChangePropertyAction #33461405)
```

Output after crash:
```bash
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Avalonia.Input.KeyBinding' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ExKingEditor.Views.ShellView.DisableGlobalShortcuts(String[] targets) in /home/runner/work/EXKing-Editor/EXKing-Editor/src/ExKingEditor/Views/ShellView.axaml.cs:line 93
   at ExKingEditor.Views.Editors.BymlView.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) in /home/runner/work/EXKing-Editor/EXKing-Editor/src/ExKingEditor/Views/Editors/BymlView.axaml.cs:line 25
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 495
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 741
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 365
   at Avalonia.Visual.SetVisualParent(Visual value) in /_/src/Avalonia.Base/Visual.cs:line 690
   at Avalonia.Visual.SetVisualParent(IList children, Visual parent) in /_/src/Avalonia.Base/Visual.cs:line 733
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 704
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 576
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 297
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 257
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 244
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 175
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at ExKingEditor.Program.Main(String[] args) in /home/runner/work/EXKing-Editor/EXKing-Editor/src/ExKingEditor/Program.cs:line 21

Aborted (core dumped)
```

**Comment by verbes4** [comment]
i also cant edit bgyml files on both arch linux and windows 10

**Comment by ArchLeaders** [comment]
I will look into it tonight, for now try using an older version and avoid using the `Right Click > Edit` in sarcs (double click instead)
