### ISSUE TITLE
Cannot save file within PlayerAttackGrave.pack.zs

### ISSUE THREAD

**Issue by mlc2020** [EXKing-Editor/EXKing-Editor#63]
I'm attempting to modify the file `PlayerAttackGrave.game__gamebalance__AttackParam.bgyml` within the `PlayerAttackGrave.pack.zs` actor pack. The error I receive on attempting to save the file (vanilla file) is

System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding codepage '65001' and fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder, Boolean throwForDestinationOverflow)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, Boolean throwForDestinationOverflow)
   at System.Text.UTF8Encoding.GetBytes(ReadOnlySpan`1 chars, Span`1 bytes)
   at NxEditor.EpdPlugin.ViewModels.BymlEditorViewModel.Write()
   at NxEditor.PluginBase.Components.Editor`1.Save(String path)

I can save the pack just fine, just not this file. I've attempted with an already modded file and with the dumped vanilla file as well.

**Comment by ArchLeaders** [comment]
This has been fixed, I just haven't been able to make the next release.

Thanks for the report.
